### ISSUE TITLE
Create DSL to describe waste collection calendars

### ISSUE THREAD

**Issue by metaodi** [metaodi/openerz#137]
Build a DSL using something like "textX" to express the rules to build a waste collection calendar.

It shouud be able to describe things like:

- Organic waste is usually collected on the 1st and 3rd Wednesday of the month
- Metall is collected on the 31.3.2024 and 30.09.2024
- Instead of 01.01.2024 the waste is collected on the 30.12.2023

The basic idea is only have minimal changes to the rules each year, generate an iCal file for the upcoming year and load it using the existing scripts.

**Comment by metaodi** [comment]
Antother approach would be to use a librars like [`recurrent`](https://github.com/kvh/recurrent) and define a YAML-like structure

```yaml
waste:
  a:
    when: weekly every Tuesday
  b:
    when: weekly every Wednesday

organic:
  when: weekly every Friday

exceptions:
   - 2024-01-01
   - 2024-01-02
   - 2024-05-01
   - 2024-08-01
   - 2024-12-25
   - 2024-12-26
 ```
